### ISSUE TITLE
Add a *.bib file

### ISSUE THREAD

**Issue by ziggystar** [terryum/awesome-deep-learning-papers#20]
That way many people could import the list into their library without hassle. The bib file should contain dois and url links to pdf files for open access papers.

On a second thought, it might be best to generate the list from the bib file automatically.

**Comment by terryum** [comment]
I agree. Many researchers are familiar with LaTeX and bib files, so I also hope to find a way to manage those list with a bib file and automatically update the Markdown list from the bib file... Do anyone have a good code for this purpose...?
