### ISSUE TITLE
Broken link: Deep Reinforcement Learning with Double Q-Learning (2016), H. Hasselt et al.

### ISSUE THREAD

**Issue by 5kyn37** [terryum/awesome-deep-learning-papers#21]
Hello.
 [Deep Reinforcement Learning with Double Q-Learning (2016), H. Hasselt et al.](http://www.aaai.org/Conferences/AAAI/2016/Papers/12vanHasselt12389.pdf) is broken. I found this job there: https://arxiv.org/pdf/1509.06461.pdf .

**Comment by terryum** [comment]
solved! thank you!
