### ISSUE TITLE
fetch_papers.py not functioning ?

### ISSUE THREAD

**Issue by HeinrichGit** [terryum/awesome-deep-learning-papers#59]
./fetch_papers.py: line 4: $'\nAuthor: doodhwala\nPython3 script to fetch the top 100 papers\n': command not found
./fetch_papers.py: line 8: directory: command not found
./fetch_papers.py: line 9: syntax error near unexpected token `('
./fetch_papers.py: line 9: `if not os.path.exists(directory):'

**Comment by aguaviva** [comment]
I just used python 27 and it worked like a charm.

All I had to do was to install 'requests' like this:
`c:\Python27\python.exe -m pip install requests`

Thanks for this awesome script :) My upcoming international flight is going to become much better now!
