### ISSUE TITLE
Addition into papers worth reading section

### ISSUE THREAD

**Issue by aqibsaeed** [terryum/awesome-deep-learning-papers#9]
I believe, [http://arxiv.org/pdf/1411.2738v4.pdf](word2vec Parameter Learning Explained
) by Xin Rong  should be a part of Paper worth reading section. It has 23 citations and explained the word embedding learning process in an excellent way!

**Comment by terryum** [comment]
I'm sorry, but I think the paper you suggested does not meet the criteria to be listed. Thank you.

Terry
